version: "3.7"
services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mariadb:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: shawoo/elms:1.0
    #image: frappe/bench:latest
    command: bash /workspace/start.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 9000:8000
    #  - 9000:9000
