version: "3.7"
services:
  elms-mariadb:
    image: mariadb:10.6
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mariadb:/var/lib/mysql

  elms-redis:
    image: redis:alpine
    restart: always

  elms:
    image: shawoo/elms:1.0
    #image: frappe/bench:latest
    restart: always
    command: bash /workspace/start.sh
    environment:
      - VER=1.0
      - SHELL=/bin/bash
    working_dir: /home/frappe
    depends_on:
      - elms-mariadb
      - elms-redis
    links:
      - elms-mariadb:mariadb
      - elms-redis:redis

    volumes:
      - .:/workspace
      - ./sites:/home/frappe/frappe-bench/sites
    ports:
      - 8000:8000
      - 9000:9000

